name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.100-preview.7.25380.108
          include-prerelease: true
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      - name: Bootstrap providers
        run: dotnet run --project tools/Nelknet.Cdktf.Bootstrap
      - name: dotnet build
        run: dotnet build
